server.port=8080
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.discovery.locator.enabled=true

# Gateway Routes
spring.cloud.gateway.routes[0].id=measurement-service
spring.cloud.gateway.routes[0].uri=lb://measurement-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/quantities/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[2].id=auth-service
spring.cloud.gateway.routes[2].uri=lb://user-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/auth/**

